feature/addPriorityControllerInfrastructure
LT-Students/DashboardService pull request #2
Opened 2023-12-14 17:43 UTC by Glunky

2023-12-14 18:12 UTC, Glunky commented on src/DashboardService.Business/Priority/CreatePriorityCommand.cs
> +  private readonly PriorityRepository _priorityRepository;
replace with interface for all commands

2023-12-14 18:45 UTC, Glunky commented on src/DashboardService.Mappers/Models/Interfaces/IPriorityInfoMapper.cs
> +public interface IPriorityInfoMapper
add autoinject

2023-12-15 10:10 UTC, SolovyovDmitry commented on src/DashboardService.Business/Priority/CreatePriorityCommand.cs
> +  private readonly PriorityRepository _priorityRepository;
self review?

2023-12-15 10:52 UTC, SolovyovDmitry requested changes

2023-12-15 10:52 UTC, SolovyovDmitry commented on src/DashboardService.Business/Priority/Interfaces/IGetAllPrioritiesCommand.cs
> +public interface IGetAllPrioritiesCommand
just GetPriorities

2023-12-15 10:52 UTC, SolovyovDmitry commented on src/DashboardService.Business/Priority/Interfaces/IGetAllPrioritiesCommand.cs
> +  Task<FindResultResponse<IEnumerable<PriorityInfo>>> ExecuteAsync();
Make T = PriorityInfo. Watch implementation

2023-12-15 10:52 UTC, SolovyovDmitry commented on src/DashboardService.Business/Priority/GetAllPrioritiesCommand.cs
> +  public Task<FindResultResponse<IEnumerable<PriorityInfo>>> ExecuteAsync()
provide filtering model which inherits BaseFindFilter

2023-12-15 10:52 UTC, SolovyovDmitry commented on src/DashboardService.Models.Dto/Responses/PriorityResponse.cs
> +public class PriorityResponse
It's so simple that I guess PriorityInfo is enough

2023-12-15 10:52 UTC, SolovyovDmitry commented on src/DashboardService.Data/Interfaces/IPriorityRepository.cs
> +  Task<IEnumerable<DbPriority>> GetAllAsync();
Just List. I don't think you will handle all the generics

2023-12-15 10:52 UTC, SolovyovDmitry commented on src/DashboardService.Data/PriorityRepository.cs
> +  public PriorityRepository([FromServices] IDataProvider provider)
You inject it with constructor so it's useless here

2023-12-15 10:52 UTC, SolovyovDmitry commented on src/DashboardService.Models.Dto/Requests/Priority/CreatePriorityRequest.cs
> +  public string PriorityName { get; set; }
Just Name

2023-12-15 10:52 UTC, SolovyovDmitry commented on src/DashboardService.Validation/Priority/CreatePriorityRequestValidator.cs
> +  public CreatePriorityRequestValidator([FromServices] IPriorityRepository reposisoty)
use this attribute only in Controller

2023-12-15 10:52 UTC, SolovyovDmitry commented on src/DashboardService.Validation/Priority/Interfaces/ICreatePriorityRequestValidator.cs
> +public interface ICreatePriorityRequestValidator : IValidator<CreatePriorityRequest> { }
can {} be replaced with ';' ?

2023-12-15 10:52 UTC, SolovyovDmitry commented on src/DashboardService/Controllers/PriorityController.cs
> +public class PriorityController : ControllerBase
PrioritiesController

2023-12-15 10:52 UTC, SolovyovDmitry commented on src/DashboardService/Controllers/PriorityController.cs
> +  [HttpPost("create")]
drop this from routes. Make it like in HWs

2023-12-15 10:52 UTC, SolovyovDmitry commented on src/DashboardService/Controllers/PriorityController.cs
> +    [FromBody] PatchPriorityRequest request,
JsonPatchDocumentT

2023-12-17 13:41 UTC, Glunky commented on src/DashboardService.Business/Priority/CreatePriorityCommand.cs
> +  private readonly PriorityRepository _priorityRepository;
)) ++

2023-12-17 13:41 UTC, Glunky commented on src/DashboardService.Mappers/Models/Interfaces/IPriorityInfoMapper.cs
> +public interface IPriorityInfoMapper
++

2023-12-17 13:41 UTC, Glunky commented on src/DashboardService.Business/Priority/Interfaces/IGetAllPrioritiesCommand.cs
> +public interface IGetAllPrioritiesCommand
++

2023-12-17 13:42 UTC, Glunky commented on src/DashboardService.Business/Priority/Interfaces/IGetAllPrioritiesCommand.cs
> +  Task<FindResultResponse<IEnumerable<PriorityInfo>>> ExecuteAsync();
++

2023-12-17 13:42 UTC, Glunky commented on src/DashboardService.Models.Dto/Responses/PriorityResponse.cs
> +public class PriorityResponse
++

2023-12-17 13:42 UTC, Glunky commented on src/DashboardService.Data/Interfaces/IPriorityRepository.cs
> +  Task<IEnumerable<DbPriority>> GetAllAsync();
++

2023-12-17 13:42 UTC, Glunky commented on src/DashboardService.Models.Dto/Requests/Priority/CreatePriorityRequest.cs
> +  public string PriorityName { get; set; }
++

2023-12-17 13:43 UTC, Glunky commented on src/DashboardService.Validation/Priority/CreatePriorityRequestValidator.cs
> +  public CreatePriorityRequestValidator([FromServices] IPriorityRepository reposisoty)
++

2023-12-17 13:43 UTC, Glunky commented on src/DashboardService.Validation/Priority/Interfaces/ICreatePriorityRequestValidator.cs
> +public interface ICreatePriorityRequestValidator : IValidator<CreatePriorityRequest> { }
no

2023-12-17 13:43 UTC, Glunky commented on src/DashboardService/Controllers/PriorityController.cs
> +public class PriorityController : ControllerBase
++

2023-12-17 13:43 UTC, Glunky commented on src/DashboardService/Controllers/PriorityController.cs
> +  [HttpPost("create")]
++

2023-12-17 13:43 UTC, Glunky commented on src/DashboardService/Controllers/PriorityController.cs
> +    [FromBody] PatchPriorityRequest request,
++

2023-12-17 15:48 UTC, closed without merging